travis:
  secure:
    BINSTAR_TOKEN: VhjFQaKZe/wsYS9r8r3NLe5e/P4goxcWqHYUF8bYeWyOm6AYJPPgqy1XyBSC426a8s10ys2z3EnwATLmNXXnWvEGuMfLDfMplSgkYCOQIaOsWB8xU99Fw9pBTB1TP8xSkAiL93+GRfO9i1OQSI1AdqU8Tr1zbGOT/xl7x4n072Qk1hXX0aTSyz5KMFosLV43KAkzD7jpWGFv4KWIWkC5b+yJ/92/IpV8DxoDDd3Inzc30oW+GR29OmwiyE6VOOsaInOq8+XnqVrHCNBYfYeLYzSY6e+rtJ+TzXh+TuRqglf5T4iIcMgdjRKNroZd8J9QY4Wl+iXzBpj29fTCiJmh48L5OnF9XqpW6RHhe4q5PoqWL3HSEE62c4ZbpOXvrFrhZzuTH3n8qt0hPSR8n144Zg9c45f4aSn8GBh/eUABalMmmW20neTfIluH92QVKvRW6VOTCfz9NIrWiYXeiouxDszlCv+tQcbTnmnwTS+YZ2QmmO0Azvorh7Tcq5SqfWtv3Mamu/GaQEKeOn0UZrip/yoafJoXAbQICYEXvn64SquImkExQzk0r0GO5gVFZp9RnNwUeLd6njGLehQ4hEBndC7a6QNehnatLPuZ2vuGhisymTi5Ql76dpaVsdV06K7ARaAmVdwS2s+6gmh8KkR/LWPgs59J9CqNJ0tvJlnF8PQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
